# -*- coding: utf-8 -*-
"""MainCode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DFa-ePAxoAy5SfKnr2leR7J-5uSUP0NB

# This notebook aims to execute automated methodological steps for research reproduction purposes. For this, the computational routine main code was divided into two parts, the first containing the "semantic search" and the next part containing the cosine similarity.

---

# FIRST STEP - SEMANTIC SEARCH

________________________________________________________________________________

To start, we will need to install and import OpenAI and input an API Key. To do that, we will need to login in https://openai.com/ and go to "View API Keys" to generate a key to input. After, wee need to install all dependencies and the correct version of the packages as showing below.
"""

!pip install nltk
!pip install pandas
!pip install openai
!pip install scipy

import nltk
from typing import List, Tuple
import pandas as pd
import scipy
import numpy as np
from openai import OpenAI
import openai

import ast
from scipy import spatial

import os

#Insert your API key
OPENAI_API_KEY = ' '
EMBEDDING_SM_MODEL= 'text-embedding-ada-002'
GPT_BOOT_MODEL = 'gpt-4.0'

"""Let's start with a simple .csv file that contains the definitions of geographical classes. After creating the file, or download, upload it to Google Colab files. Once the file is uploaded, read it into a pandas data frame."""

df = pd.read_csv('words_PT1_frmt.csv')
print(df)

"""Transform the data into Embenddinigs and save the vector coordinates into a "word_embeddings.csv" file, showed as a output with respectives embenddings."""

def TokenizeLargerlists(text):
  nltk.download('punkt')
  sentences= nltk.sent_tokenize(text)
  return sentences

# Defina as variáveis globais como a chave da API e o modelo de embeddings
#Insert your API key
OPENAI_API_KEY = ' '
EMBEDDING_SM_MODEL = 'text-embedding-ada-002'
import nltk
from typing import List, Tuple
import pandas as pd
import scipy
from openai import OpenAI
import openai
import ast
from scipy import spatial
import os
GPT_BOOT_MODEL = 'gpt-4.0'
!pip install --upgrade openai

# Inicializa o cliente OpenAI
client = OpenAI(api_key=OPENAI_API_KEY)

def createAndSaveEmbeddings(input_csv):
    """
    Cria embeddings para os textos de um arquivo CSV e os salva em outro arquivo CSV.

    Args:
        input_csv (str): Caminho para o arquivo CSV de entrada com textos.
    """
    # Ler o arquivo CSV de entrada

    sentences = df.iloc[:, 0].tolist()  # Assumindo que os textos estão na primeira coluna

    BATCH_SIZE = 1000  # Defina o tamanho do lote para processar os textos

    embeddings = []  # Lista para armazenar os embeddings

    # Processa os textos em lotes
    for batch_start in range(0, len(sentences), BATCH_SIZE):
        batch_end = batch_start + BATCH_SIZE
        batch = sentences[batch_start:batch_end]  # Extrai um lote de textos
        print(f"Processando lote {batch_start} a {batch_end-1}")

        # Obtém os embeddings para o lote de textos usando o novo método client.embeddings.create()
        response = client.embeddings.create(input=batch, model=EMBEDDING_SM_MODEL)

        # Adiciona os embeddings à lista
        batch_embeddings = [e.embedding for e in response.data] # Adjusted to access the embedding attribute
        embeddings.extend(batch_embeddings)

    # Cria um DataFrame a partir dos textos e embeddings
    df_embeddings = pd.DataFrame({"embedding": embeddings})

    # Salva o DataFrame em um arquivo CSV
    df_embeddings.to_csv("saved_embeddings.csv", index=False)

df['embedding'] = df['TEXT'].apply(lambda x: client.embeddings.create(input=[x], model='text-embedding-ada-002').data[0].embedding)
df.to_csv('word_embeddings.csv', index=False)

df = pd.read_csv('word_embeddings.csv')
df['embedding'] = df['embedding'].apply(eval).apply(np.array)
df

import torch
from torch import cosine_similarity

search_term = input('Enter a search term: ')

search_term_vector = client.embeddings.create(input=search_term, model=EMBEDDING_SM_MODEL)
search_term_vector

"""After that, calculate the cosine similarity between the search term and all the data input"""

search_term_embedding = torch.tensor(search_term_vector.data[0].embedding)

"""In this step, the responses are showed by ascending values"""

df['similarities'] = df['embedding'].apply(lambda x: cosine_similarity(torch.tensor(x), search_term_embedding, dim=0).item())

df

df.sort_values("similarities", ascending=False).head(100)

"""# SECOND STEP - COSSINE SIMILARITY AND CORRELATION MATRIX

We will start by importing the transformer library.
"""

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer

model = SentenceTransformer('all-mpnet-base-v2')

model

"""We will import the most current and efficient transformer model for semantic similarity 'all-mpnet-base-v2'

Declaring the vector sentences of words to be transformed (same definitions as in the woords.csv file), to demostrate other way to do it.
"""

sentences = [
"Todas as terras que nao sao classificadas como florestas ou outras terras arborizadas.",
"Campo e uma forma particular de ocorrencia (normalmente cirscunstancial) de uma vegetacao e se caracterizada pelas fisionomias Gramineo Lenhosas da Campinarana da Savana (Cerrado) da Savana Estepica (Caatinga) e da Estepe (Campos do sul do Brasil)",
"Entende como areas campestres as diferentes categorias de vegetacao fisionomicamente bem diversa da florestal esparsamente distribuido sobre um tapete gramineo lenhoso",
"Areas de relevo plano ou suave ondulado recobertas por vegetacao herbacea continua",
"Areas abertas cobertas por gramineas homogeneas com pouca ou nenhuma vegetacao alta. Outras areas homogeneas de vegetacao semelhante a gramineas (folhas semelhantes a laminas) que parecem diferentes de arvores e arbustos. Cereais e gramineas selvagens sem nenhuma parcela humana obvia (ou seja, sem um campo estruturado).",
"Vegetacao predominantemente herbacea com raros arbustos e ausencia de arvores",
"entende se como areas campestres as diferentes categorias de vegetacao fisionomicamente bem diversa da florestal ou seja aquelas que se caracterizam por um estrato predominantemente arbustivo esparsamente distribuido sobre um tapete gramineo lenhoso Encontram se disseminadas por diferentes regioes fitogeograficas compreendendo diferentes tipologias primarias",
"A Estepe Gramineo Lenhosa e o tipo mais representativo dos campos do sul do Brasil impressionando pela grande extensao e monotonia fitofisionomica principalmente no Estado do Rio Grande do Sul Certamente isto se deve a forma de manejo utilizada ao longo de muitas decadas que adota dentre outros instrumentos o fogo",
"Terras que se estendem como outra terra florestada com mais de 0,5 hectares com arvores com mais de 5 metros de altura e com cobertura de copa de 5 a 10 por cento ou arvores capazes de atingir esses limites ou com uma cobertura combinada de arbustos e arvores acima de 10 por cento. Nao inclui terra predominantemente sob uso agricola ou urbano.",
"Vegetacao com fisionomia herbacea e arbustiva com arbustos e subarbustos espacados entre si Tambem pode ser classificada como campo sujo a vegetacao secundaria em estagio inicial de regeneracao com densidade baixa de individuos",
"As maiores extensoes de Estepe Parque foram observadas na parte leste do Planalto das Araucarias  na porcao central do Planalto Rio Grandense do Sul e nos terrenos divisores de agua dos Rios Santa Maria e Ibirapuita Distinguem se dois nitidos estratos a) um superior arboreo baixo com individuos esparsos de varias familias sendo as mais representativas Lythraceae e Anacardiaceae e b) um inferior com predominio das gramineas Paspalum notatum Flugge (grama forquilha) e Axonopus fissifolius (Raddi) Kuhlm (grama tapete ou grama jesuita) Andropogon lateralis Ness (capim caninha) e Stipa spp (capim flechinha) alem de plantas anuais (terofitas) que imprimem ao Estepe Parque variacoes de tonalidade e de valor agrostologico",
"Terrenos considerados como Outros terrenos que sao predominantemente agricolas ou de uso urbano e possuem manchas de cobertura arborea com mais de meio hectares com cobertura de copa superior a 10 por cento de arvores capazes de atingir uma altura de 5 metros na maturidade Inclui especies de arvores florestais e nao florestais",
"Vegetacao predominantemente herbaceo arbustiva com a presenca eventual de arvoretas pouco desenvolvidas de ate dois metros de altura Abrange um complexo de vegetacao que agrupa paisagens em microrrelevos com especies tipicas ocupando trechos de afloramentos rochosos Geralmente ocorre em altitudes superiores a 900 metros ocasionalmente a partir de 700 metros em areas onde ha ventos constantes e variacoes extremas de temperatura com dias quentes e noites frias",
"entende se como areas campestres as diferentes categorias de vegetacao fisionomicamente bem diversa da florestal ou seja aquelas que se caracterizam por um estrato predominantemente arbustivo esparsamente distribuido sobre um tapete gramineo lenhoso  Encontram se disseminadas por diferentes regioes fitogeograficas compreendendo diferentes tipologias primarias",
"E encontrada principalmente na regiao do Escudo rio grandense em terrenos divisores de agua do sistema hidrografico Camaqua Piratini Jaguarao (RS) Caracteriza se especialmente pela dominancia de solos rasos com ou sem afloramentos rochosos e ate solos medianamente profundos Nesta formacao as plantas distribuem se por dois nitidos estratos O primeiro superior esparso perenifoliado ligado ou nao a florestas de galeria e formado predominantemente por arvores baixas e arbustos no qual destacam se as especies de origem andino argentina",
"Vegetacao cultivada e aquela que possui especies vegetais cultivadas com objetivos ecologico de alimentacao aproveitamento industrial ou para protecao do solo contra erosao",
"Terras que se estendem por mais de 0,5 hectares com arvores maiores que 5 metros e uma cobertura de copa de mais de 10 por cento ou arvores capazes de atingir esses limites in situ. Nao inclui terras que sao predominantemente sob uso agricola ou urbano.",
"No sentido amplo a terra agricola pode ser definida como terra utilizada para a producao de alimentos fibras e commodities do agronegocio Inclui todas as terras cultivadas caracterizadas pelo delineamento de areas cultivadas ou em descanso podendo tambem compreender areas alagadas Podem se constituir em zonas agricolas heterogeneas ou representar extensas areas de plantations Encontram se inseridas nesta categoria as lavouras temporarias lavouras permanentes pastagens plantadas silvicultura e areas comprovadamente agricolas cujo uso nao foi identificado no periodo do mapeamento",
"Em escala regional e exploratoria o maximo a ser feito resume se em separar as culturas ciclicas das permanentes Nas escalas de semidetalhe e de detalhe a separacao do tipo de agricultura realizada pode e deve ser detectada pelo menos as mais importantes como a agricultura ciclica",
"Cereais, gramineas e culturas plantadas/plantadas por humanos.",
"Especie vegetal cultivada com extracao para beneficiamento Abrange as areas plantadas ou em preparo para o plantio de culturas de curta duracao (em torno de um ano) e que necessitam geralmente de novo plantio apos cada colheita tais como arroz algodao milho trigo flores e hortalicas",
"Cultivo de plantas de curta ou media duracao geralmente com ciclo vegetativo inferior a um ano que apoos a producao deixam o terreno disponivel para novo plantio Dentre as culturas destacam se as de graos e cereais as de bulbos raizes tuberculos e hortalicas Incluem ainda as plantas horticolas floriferas medicinais aromaticas e condimentares de pequeno porte que muitas vezes sao cultivadas em estruturas como estufas ripados e telados As lavouras semipermanentes como cana de acucar e mandioca bem como as culturas de algumas forrageiras destinadas ao corte tambem estao incluidas nessa categoria",
"Nas escalas de semidetalhe e de detalhe a separacao do tipo de agricultura realizada pode e deve ser detectada pelo menos as mais importantes como a agricultura ciclica de soja trigo arroz e cana de acucar sendo que algumas culturas como a do feijao no Municipio de Irece na Bahia podem ser perfeitamente separadas",
"Especie vegetal cultivada permanentemente sem extracao para beneficiamento Compreende a area plantada ou em preparo para o plantio de culturas de longa duracao tais como cafe laranja cacau banana e uva que apos a colheita nao necessitam de novo plantio produzindo por varios anos sucessivos",
"o cultivo de plantas perenes isto e de ciclo vegetativo de longa duracao Essas plantas produzem por varios anos sucessivos sem a necessidade de novos plantios apos colheita sendo utilizadas tecnicas de cultivo tradicional organico assim como o cultivo de plantas modificadas geneticamente Compreende tambem a producao de sementes e mudas das plantas desta classe quando atividade complementar ao cultivo Nesta categoria estao especies frut?feras como laranjeiras cajueiros coqueiros macieiras e bananeiras especies produtoras de fibras como coco da baia especies oleaginosas cultivos diversificados e as especies como cafeeiros seringueiras e cacaueiros em sistemas que combinam ou nao culturas agricolas com florestas",
"A agricultura permanente de cafe laranja e cacau e facilmente detectada apos verificacao dos padroes de imagem com a verdade terrestre",
"Especie vegetal cultivada com ou sem extracao para beneficiamento Abrange as areas plantadas ou em preparo para o plantio de culturas de longa ou curta duracao",
"Cultivo de plantas de curta ou media duracao geralmente com ciclo vegetativo inferior a um ano que apos a producao deixam o terreno disponivel para novo plantio Dentre as culturas destacamse as de graos e cereais as de bulbos raizes tuberculos e hortalicas Incluem ainda as plantas horticolas floriferas medicinais aromaticas e condimentares de pequeno porte que muitas vezes sao cultivadas em estruturas como estufas ripados e telados As lavouras semipermanentes como cana de acucar e mandioca bem como as culturas de algumas forrageiras destinadas ao corte tambem estao incluidas nessa categoria",
"Nas escalas de semidetalhe e de detalhe a separacao do tipo de agricultura realizada pode e deve ser detectada pelo menos as mais importantes como a agricultura ciclica de soja trigo arroz e cana de acucar  sendo que algumas culturas como a do feijao no Municipio de Irece na Bahia podem ser perfeitamente separadas",
"Area de floresta e outras terras arborizadas com vegetacao de mangue",
"Mangue e uma formacao pioneira de influencia fluvio marinha de ambiente salobro situada na desembocadura de rios e regatos no mar onde nos solos limosos (manguitos) cresce uma vegetacao especializada adaptada a salinidade de aguas",
"Area de floresta e outras terras arborizadas com vegetacao de mangue.",
"O Manguezal e a comunidade microfanerofitica de ambiente salobro situada na desembocadura de rios e regatos no mar onde nos solos limosos (manguitos) cresce uma vegetacao especializada adaptada a salinidade das aguas com a seguinte sequencia Rhizophora mangle L. Avicennia sp. cujas especies variam conforme a latitude e Laguncularia racemosa (L.) C. F. Gaertn. que cresce nos locais mais altos so atingidos pela preamar",
"Areas de qualquer tipo de vegetacao com mistura obvia de agua. Nao presuma que uma area esta inundada se a inundacao for vista em outra imagem. Areas sazonalmente inundadas que sao uma mistura de grama/arbustos/arvores/solo descoberto.",
"Terrenos com mais de meio hectares com arvores com altura superior a 5 metros e uma cobertura de copa superior a 10 por cento",
"Ecossistema litoraneo que ocorre em terrenos baixos sujeitos a acao das mares formado por vasas lodosas recentes ou arenosas as quais se associa predominantemente a vegetacao natural conhecida como mangue com influencia fluviomarinha tipica de solos limosos de regioes estuarinas e com dispersao descontinua ao longo da costa brasileira entre os Estados do Amapa e de Santa Catarina",
"Manguezal arboreo Formacao Pioneira com influencia fluviomarinha",
"Nesta comunidade pode faltar um ou mesmo dois desses elementos E frequente observar se o Manguezal so de Rhizophora como o do Estado do Maranhao ou so de Avicennia como o do Estado do Amapa pois a Laguncularia so aparece quando existe terreno firme nos terracos e nas planicies salobras do fundo das baias e dos rios Em algumas dessas planicies justamente quando a agua do mar fica represada pelos terracos dos rios a area salobra e densamente povoada por Spartina alterniflora Loisel. e Blutaparon portulacoides (A. St.Hil.) Mears. (Amaranthaceae) que imprimem ao campo salino o carater de um manguezal camefitico",
"Areas situadas em regioes com frequencias de inundacoes intermediarias entre mares de sizigias e de quadratura com solos cuja salinidade varia entre 100 (cem) e 150 (cento e cinquenta) partes por 1.000 (mil) onde pode ocorrer a presenca de vegetacao herbacea especifica",
"O Manguezal e a comunidade microfanerofitica de ambiente salobro situada na desembocadura de rios e regatos no mar onde nos solos limosos (manguitos) cresce uma vegetacao especializada adaptada a salinidade das aguas com a seguinte sequencia Rhizophora mangle L. Avicennia sp. cujas especies variam conforme a latitude e Laguncularia racemosa (L.) C. F. Gaertn. que cresce nos locais mais altos so atingidos pela preamar",
"Floresta e um tipo de vegetacao caracterizado por arvores de porte alto que na Amazonia podem atingir alturas superiores a 40 m. Em determinadas areas e bastante significativa a presen?a de palmeiras cipos bambus e sororocas junto com os individuos arboreos da floresta. Em outros locais fora da Amazonia durante alguns meses devido a falta de chuvas a floresta perde parte de suas folhas (decidualidade) chegando em algumas areas a perda ser superior a 50 porce0nto. No sul do Pais principalmente e marcante a presenca da especie conhecida como pinheiro do parana na composicao da floresta",
"considera se como florestais as formacoes arboreas com porte superior a 5 m incluindo se ai as fisionomias da Floresta Densa (estrutura florestal com cobertura superior continua) da Floresta Aberta (estrutura florestal com diferentes graus de descontinuidade da cobertura superior conforme seu tipo (com cipo bambu palmeira ou sororoca) da Floresta Estacional (estrutura florestal com perda das folhas dos estratos superiores durante a estacao desfavoravel (seca e frio) alem da Floresta Ombrofila Mista (estrutura florestal que compreende a area de distribuicao natural da Araucaria angustifolia elemento marcante nos estratos superiores que geralmente forma cobertura continua) e das areas de mangues",
"Termo semelhante a mata no sentido popular tem conceituacao bastante diversificada mas firmada cientificamente como sendo um conjunto de sinusias dominado por fanerofitos de alto porte com quatro estratos bem definidos (herbaceo arbustivo arvoreta arboreo baixo e arboreo). Porem alem destes parametros acrescenta se o sentido de altura para diferencia la das outras formacaes lenhosas campestres. Assim entao uma formacao florestal apresenta dominancia de duas subformas de vida de fanerofitos macrofaneroofitos com alturas variando entre 30 e 50 m e mesofanerofitos cujo porte situa se entre 20 e 30 m de altura. As florestas caracterizam se pelo adensamento de arvores altas com reducao da quantidade de luz que chega ao solo o que limita o desenvolvimento das sinusias herbacea e arbustiva",
"Qualquer agrupamento significativo de vegetacao densa, tipicamente com uma copa fechada ou densa. Mais alto e mais escuro que a vegetacao ao redor (se cercado por outra vegetacao).",
"Area umida e aquela que possui uma lamina dagua com pequena profundidade tipica de regioes com vegetacao do tipo brejo ou pantano ou aquela que possui a sua superficie permanentemente encharcada",
"Os corpos dagua interiores geralmente incluem grandes rios, lagos e reservatorios de agua.",
"Nos pantanos o genero cosmopolita Typha fica confinado a um ambiente especializado diferente dos generos Cyperus e Juncus que seo exclusivos das ereas pantanosas dos trepicos. Estes tres generos dominam nas depressoes brejosas em todo o Pais",
"As massas de agua interiores geralmente incluem grandes rios lagos e reservatorios de agua",
"Terreno onde ocorre areia podendo ser umido ou nao",
"Trata se de comunidades vegetais das planicies aluviais que refletem os efeitos das cheias dos rios nas epocas chuvosas ou entao das depressoes alagaveis todos os anos. Nestes terrenos aluviais conforme a quantidade de agua empocada e ainda o tempo que ela permanece na area. Nas planicies alagaveis mais bem drenadas ocorrem comunidades campestres e os generos Panicum e Paspalum dominam em meio ao camefito do genero Thalia. Nos terracos mais enxutos dominam nanofanerofitos dos generos Acacia e Mimosa juntamente com varias familias pioneiras como Solanaceae Asteraceae Myrtaceae e outras de menor importancia sociologica",
"Mistura de terra e agua",
"Ambientes Lentico que nao possuem correnteza nao possuem fluxo continuo como lagos lagoas brejo ou pantano",
"Trata se de comunidades vegetais das planicies aluviais que refletem os efeitos das cheias dos rios nas epocas chuvosas ou entao das depressoes alagaveis todos os anos. Nestes terrenos aluviais conforme a quantidade de agua empo?ada e ainda o tempo que ela permanece na area. Nos pantanos o genero cosmopolita Typha fica confinado a um ambiente especializado diferente dos generos Cyperus e Juncus que sao exclusivos das areas pantanosas dos tropicos. Estes tres generos dominam nas depressoes brejosas em todo o Pais",
"Caatinga e classificada como Savana Estepica pelo IBGE ocorre predominantemente no Nordeste. E composta por individuos arbooreos (muitos deles espinhosos) com esgalhamento acentuado. Na epoca seca perdem as folhas (decidualidade). Neste tipo de vegetacao e constante a ocorrencia de cactos. Apresentam quatro fisionomias Florestada Arborizada Parque e Gramineo Lenhosa sendo a ultima pelas caracteristicas fisionmicas contemplada na classe Campo. A savana estepica tambem ocorre nos campos de Roraima Chaco Sul Mato Grossense e Parque de Espinilho da barra do Rio Quarai (area fora do Nordeste)",
"Se caracterizam por um estrato predominantemente arbustivo esparsamente distribuido sobre um tapete gramineo lenhoso. Encontram se disseminadas por diferentes regioes fitogeograficas compreendendo diferentes tipologias primarias savanas estepes planaltinas",
"Binomio criado por Trochain (1955) para designar uma formacao africana tropical proxima a Zona Holartica. No dizer do mesmo naturalista a denominacao estepica deveria ser precedida do termo Savana por ser fisionomia tropical na qual arvores arbustos e ervas estao presentes de forma relevante sem uma clara dominancia fisionmica das arvores. Esta fisionomia foi extrapolada como sinonimo universalizado do termo indigena tupi guarani Caatinga que no dizer do botanico Dardano de Andrade Lima (1982) caracteriza muito bem os tipos de vegetacao das areas aridas nordestinas interplanalticas arrasadas (Sertao)",
"Uma mistura de pequenos aglomerados de plantas ou plantas individuais espalhadas por uma paisagem que apresenta solo e rocha expostos. Clareiras cheias de arbustos em florestas densas que claramente nao sao mais altas do que as arvores. Elas parecem mais acinzentadas/marrons devido a cobertura de folhas menos densa.",
"Arvores dispersas com cobertura de copa inferior a 10 por cento, pequenos grupos de arvores com menos de 0,5 hectares e linhas de arvores com menos de 20 metros de largura.",
"Este subgrupo de formacao tambem conhecido como campo espinhoso apresenta caracteresticas floresticas e fisionomicas bem tipicas ou seja um extenso tapete graminoso salpicado de plantas lenhosas anas espinhosas. O terreno e coberto inteiramente pelo capim panasco (Aristida sp.) especie hemicriptofita que se apresenta com um aspecto de palha na seca e que enverdece na epoca das aguas. Este campo e entremeado de nanofanerofitos espinhosos despidos de folhagem na seca e cheios de folhas na epoca das chuvas pertencentes ao genero Jatropha (pinheo brabo) da familia Euphorbiaceae de distribuicao pantropical",
"Este subgrupo de formacao puramente herbaceo constitui se na verdadeira Campina. Surge ao longo das planicies encharcadas dos rios de aguas pretas e tambem nas depressoes fechadas dos interfluvios tabulares  capeados pelo Espodossolo. No caso das depressoes  em geral com formas circulares  o encharcamento e a fisionomia pantanosa limitam se ao periodo chuvoso  tornando se bastante arida e seca no auge da estacao desfavoravel. Neste periodo  em certas areas  ocorrem queimadas que tem modificado bastante sua estrutura e composicao.",
"Cerrado é caracterizada por dois estratos: um graminoso e outro arbóreo com indivíduos tortuosos e ramificação irregular. Ocorre prioritariamente no Brasil Central e em outras partes do País recebe nomes locais como: “tabuleiro”, “agreste”, “chapada” no nordeste, “campina” ou “gerais” no norte de Minas Gerais, Tocantins e Bahia, “lavrado” em Roraima, dentre outras denominações. Apresenta quatro fisionomias/ Florestada (Cerradão), Arborizada (Campo Cerrado), Parque (Campo-Sujo-de-Cerrado) e Gramíneo-Lenhosa (Campo-Limpo-deCerrado), sendo a última, pelas características fisionômicas, contemplada na classe “Campo”. Também conhecida como savana.",
"Se caracterizam por um estrato predominantemente arbustivo  esparsamente distribuido sobre um tapete gramineo-lenhoso.",
"Prevalecem nesta fisionomia  quando natural  os gramados entremeados por plantas lenhosas raquiticas  que ocupam extensas areas dominadas por hemicriptofitos e que  aos poucos  quando manejados atraves do fogo ou pastoreio  sendo substituidos por geofitos que se distinguem por apresentar colmos subterraneos  portanto mais resistentes ao pisoteio do gado e ao fogo",
"Subgrupo de formacao constituido essencialmente por um estrato graminoide  integrado por hemicriptofitos e geofitos de floristica natural ou antropizada  entremeado por nanofanerofitos isolados  com conotacao tipica de um Parque Ingles (Parkland). A Savana Parque de natureza antropica e encontrada em todo o Pais  enquanto a natural ocorre algumas vezes com feicao de campos litossolicos e ou rupestres. Em areas encharcadas de depressoes periodicamente inundadas  ocorrem as tipologias naturais de Cerrado de Pantanal  com denominacoes regionais diversas  caracterizadas pela presenca de covoais  monchoes ou murundus",
"A Savana (Cerrado) e conceituada como uma vegetacao xeromorfa que ocorre sob distintos tipos de clima. Reveste solos lixiviados aluminizados apresentando sinusias de hemicriptofitos geofitos camefitos e fanerofitos ligotroficos de pequeno porte com ocorrencia em toda a Zona Neotropical e prioritariamente no Brasil Central. Em outras partes do Pais recebe nomes locais como Tabuleiro Agreste e Chapada na Regiao Nordeste Campina ou Gerais no norte dos Estados de Minas Gerais Tocantins e Bahia e Lavrado no Estado de Roraima entre outras denominacoes. A Savana (Cerrado) foi subdividida em subgrupos de formacao",
"Savana Arborizada (Campo-Cerrado) Savana Parque, Savana Gramíneo-Lenhosa"
"Subgrupo de formacao no qual predominam arbustos cespitosos e ervas  densamente distribuidos e eventualmente entremeados por arvores baixas  geralmente entendida como uma das fisionomias de Campina Amazonica  que ocorrem preferencialmente nas areas das depressoes fechadas com Espodossolos. Na sua maioria  as especies sao as mesmas da Campinarana Arborizada  sendo a principal caracteristica diferencial entre elas a altura de seus componentes  que raramente ultrapassam 2 m. Essa reducao do porte arboreo esta na dependencia do nivel e da duracao do encharcamento do solo e seu grau de oligotrofismo  fatores que influenciam ainda na densidade dos individuos e na coloracao das folhas  que passam ao verde palido  bem como na maior tortuosidade dos troncos  resultando numa fisionomia que se caracteriza por um porte raquitico. Nesta formacao  tambem se inclui a fisionomia arbustiva densa de ?Caatinga-Gapo   as vezes denominada como ?varetal   tipica das planicies e areas cujo encharcamento e quase permanente.",
"Campinarana e um tipo de vegetacao lenhosa que ocorre na Amazonia brasileira geralmente em depressoes fechadas revestindo solos arenosos. Apresenta quatro fisionomias Florestada Arborizada Arbustiva e Gramineo Lenhosa sendo a ultima pelas caracteristicas fisionomicas contemplada na classe Campo",
"caracterizam por um estrato predominantemente arbustivo esparsamente distribuido sobre um tapete gramineo lenhoso.",
"Usado para designar as formacoes campestres do sul do Pais . Este tipo de vegetacao ocorre predominantemente em areas fronteiricas da Colombia e Venezuela nas Bacias dos Rios Negro e Branco e sob a forma de disjuncoes por toda a Amazonia adaptado ao solo Espodossolo. As campinaranas ocorrem em areas planas e alagadas e apresentam fisionomia bastante variada desde formacooes campestres ate florestais com arvores finas",
"Terrenos que incluem terras de cultivo itinerante abandonadas com regeneracao de arvores que atingiram ou devem atingir uma copa de pelo menos 10 por cento e altura de arvores de pelo menos 5 metros.",
"Reflorestamento e uma area onde foi implantada uma floresta em uma area naturalmente florestal que por acao antropica ou natural perdeu suas caracteristicas originais",
"Plantio ou formacao de macicos com especies florestais nativas ou exoticas. Nesta definicao nao se considera se o plantio e realizado em areas anteriormente povoadas com especies florestais ou nao considera se reflorestamento todas as areas povoadas com essencias florestais independentemente do ambiente. Os plantios podem ser heterogeneos homogeneos e consorciados",
"No sistema secundario (antropico) estao incluidas todas as comunidades secundarias brasileiras. Sao aquelas areas onde houve intervencao humana para o uso da terra seja com finalidade mineradora agricola ou pecuaria descaracterizando a vegetacao primaria. Assim sendo essas areas quando abandonadas reagem diferentemente de acordo com o tempo e a forma de uso da terra",
"As comunidades vegetais que recebem influencia direta das aguas do mar apresentam generos caracteristicos das praias Remirea e Salicornia.",
"Vegetacao de restinga e uma formacao pioneira de influencia marinha caracterizada pelas comunidades vegetais que recebem influencia direta das aguas do mar. Apresenta tres fisionomias arborea (do pontal rochoso) arbustiva (das dunas) e herbacea (das praias)",
"Se caracterizam por um estrato predominantemente arbustivo esparsamente distribuido sobre um tapete gramineo lenhoso. campos rupestres das serras costeiras e campos hidroarenosos litoraneos (restinga). Formacoes pioneiras de influencia marinha (Restinga arbustiva das dunas e herbacea das praias)",
"As comunidades vegetais que recebem influencia direta das aguas do mar apresentam generos caracteristicos das praias Remirea e Salicornia. Seguem se em areas mais altas afetadas pelas mares equinociais  as conhecidas Ipomoea pescaprae alem dos generos Paspalum e Hidrocotyle. As duas primeiras sao plantas escandentes e estoloniferas que atingem as dunas contribuindo para fixa las.",
"Nas planicies alagaveis mais bem drenadas  ocorrem comunidades campestres e os generos Panicum e Paspalum dominam em meio ao camefito do genero Thalia. Nos terracos mais enxutos  dominam anofanerofitos dos generos Acacia e Mimosa  juntamente com varias familias pioneiras  como Solanaceae  Asteraceae  Myrtaceae e outras de menor importancia sociologica.",
"Brejo ou pantano e uma formacao pioneira de influencia fluvial e ou lacustre das planicies aluviais que refletem os efeitos de cheias dos rios nas epocas chuvosas ou das depressoes alagaveis todos os anos. Nestes terrenos aluviais conforme a quantidade de agua empocada e o tempo que ela permanece na area as comunidades vegetais vao desde a pantanosa ate os terracos alagaveis temporariamente onde em muitas areas as palmeiras se agregam constituindo o acaizal e o buritizal. Apresenta tres fisionomias palmeiral (buritizal carandazal carnaubal e outras) arbustiva e herbacea.",
"Ambientes Lêntico, que não possuem correnteza, não possuem fluxo contínuo, como: lagos, lagoas, brejo ou pântano",
"Trata-se de comunidades vegetais das planícies aluviais que refletem os efeitos das cheias dos rios nas épocas chuvosas, ou, então, das depressões alagáveis todos os anos. Nestes terrenos aluviais, conforme a quantidade de água empoçada e ainda o tempo que ela permanece na área, as comunidades vegetais pdem ser pantanosa criptofítica (hidrófitos). Nos pântanos, o gênero osmopolita Typha fica confinado a um ambiente especializado, diferente dos gêneros Cyperus e Juncus, que são exclusivos das áreas pantanosas dos trópicos. Estes três gêneros dominam nas depressões brejosas em ",
"Nos pântanos, o gênero cosmopolita Typha fica confinado a um ambiente especializado, diferente dos gêneros Cyperus e Juncus, que são exclusivos das áreas pantanosas dos trópicos. Estes três gêneros dominam nas depressões brejosas em todo o País",
"Nas planícies alagáveis mais bem-drenadas, ocorrem comunidades campestres e os gêneros Panicum e Paspalum dominam em meio ao caméfito do gênero Thalia. Nos terraços mais enxutos, dominam anofanerófitos dos gêneros Acacia e Mimosa, juntamente com várias famílias pioneiras, como: Solanaceae, Asteraceae, Myrtaceae e outras de menor importância sociológica.",
"Duna e um monte de areia movel ou nao acumulado nas areas litoraneas ou continentais pela acao de deposicao do vento dominante",
"referem se as areas de praias  dunas e extensoes de areia ou seixos no litoral ou no continente incluindo leitos de canais de fluxo com regime torrencial dunas com vegetacao esparsa ou sem vegetacao desenvolvidas no interior do continente ou nas zonas de praias areas de extracao abandonadas e sem cobertura vegetal.",
"As dunas sao as areas compostas somente por areia. Todavia quando apresentam alguma vegetacao sao identificadas como Formacao Pioneira",
"Areas de rocha ou solo contendo pouca ou nenhuma vegetacao. Grandes areas de areia e desertos com pouca ou nenhuma vegetacao. Grandes redes individuais ou densas de estradas de terra.",
"Rocha e uma formacao natural de minerais agregados resultante de um processo geologico",
"Estas areas referem se tanto a ambientes naturais como rochas desnudas ou praias quanto a ambientes antropicos decorrentes da degradacao provocada pelas atividades humanas como extracao de minerais",
"Os afloramentos rochosos sao aquelas areas que nao apresentam nenhum tipo de vegetacao somente a rocha. Quando ocorrer alguma vegetacao nas fendas ou em outras situacaes sera identificada como",
]

# Transforming into embeddings
embeddings = model.encode(sentences)

embeddings.shape

"""We will also import additional libraries and introduce the openAI key

Applying cosine similarity of all data to all data in a correlation matrix (sim).
"""

import numpy as np
from sentence_transformers.util import cos_sim

sim = np.zeros((len(sentences), len(sentences)))

for i in range(len(sentences)):
    sim[i:,i] = cos_sim(embeddings[i], embeddings[i:])

np.set_printoptions(threshold=np.inf, linewidth=np.inf)
print(sim)

"""Presentation of the correlation matrix in heatmap format"""

import matplotlib.pyplot as plt
import seaborn as sns
sns.set(rc={'figure.figsize':(60, 60)})

sns.heatmap(sim, annot=True, cmap='Greens')